# Generated by Django 4.1.7 on 2023-03-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserViews',
            fields=[
                ('v_sno', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=255)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
